# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Wilhelmina
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"." \
    -l/"$(INHERIT)/" \
    -l$(Qt_LIBS_) \
    -lCrypt32 \
    -l"/"C:/Program \
    -lFiles/OpenSSL-Win64/lib/libcrypto/"" \
    -l/"C:/src/vcpkg/packages/libssh_x64-windows/debug/lib/ssh/"
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(Wilhelmina.pri)
win32:RC_FILE = Wilhelmina.rc
