# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./Crypto.h \
    ./CryptoState.h \
    ./CustomListWidgetItem.h \
    ./CustomQTableWidgetItem.h \
    ./DuplicateEntry.h \
    ./Entries.h \
    ./MyNativeEventFilter.h \
    ./SSHsync.h \
    ./PasswordGenerator.h \
    ./resource.h \
    ./Wilhelmina.h \
    ./AddNewEntry.h \
    ./AboutDialog.h \
    ./DuplicateDialog.h \
    ./IdleFilter.h \
    ./PreferencesDialog.h \
    ./MasterPasswordDialog.h
SOURCES += ./AboutDialog.cpp \
    ./AddNewEntry.cpp \
    ./Crypto.cpp \
    ./CryptoState.cpp \
    ./CustomListWidgetItem.cpp \
    ./CustomQTableWidgetItem.cpp \
    ./DuplicateDialog.cpp \
    ./DuplicateEntry.cpp \
    ./Entries.cpp \
    ./IdleFilter.cpp \
    ./MasterPasswordDialog.cpp \
    ./MyNativeEventFilter.cpp \
    ./PasswordGenerator.cpp \
    ./PreferencesDialog.cpp \
    ./SSHsync.cpp \
    ./Wilhelmina.cpp \
    ./main.cpp
FORMS += ./AddNewEntry.ui \
    ./DialogAbout.ui \
    ./DuplicatesDialog.ui \
    ./MasterPasswordDialog.ui \
    ./Preferences.ui \
    ./Wilhelmina.ui
RESOURCES += Wilhelmina.qrc
